### ISSUE TITLE
missing consumer proguard file.

### ISSUE THREAD

**Issue by wiensmit** [Mopinion-com/mopinion-sdk-android#2]
Event based forms currently don't work unless you keep the whole SDK with 

-keep class com.mopinion.mopinion_android_sdk** { *; }

This can be improved on by providing a consumer proguard file

**Comment by ManuelCrovetto** [comment]
Hello @wiensmit,

Thank you for writing us. 
Can you please provide more details about this issue? 

Thanks.

**Comment by ManuelCrovetto** [comment]
The consumer file was provided in v1.0.16. Let us know if the issue persists.
