### ISSUE TITLE
Formstate stays in Loading state forever

### ISSUE THREAD

**Issue by Sammekl** [Mopinion-com/mopinion-sdk-android#3]
I tried to integrate this SDK into our app, replacing the old SDK. We're using the same deployment and form keys.

However, the form stays in loading state and thus show the ProgressBar. Filling and sending the form works fine. The state changes to send.

![Screenshot 2023-08-25 at 09 18 57](https://github.com/Mopinion-com/mopinion-sdk-android/assets/3931308/052aed5b-8fb1-4b0f-adb9-4a67d71a7c3c)

![Screenshot 2023-08-25 at 09 19 39](https://github.com/Mopinion-com/mopinion-sdk-android/assets/3931308/e030c6a9-7853-4109-9009-f940285ee346)

From logcat:
```
Formstate: Loading(isLoading=true)
Formstate: Loading(isLoading=true)
Formstate: Loading(isLoading=false)

// When sent:
Formstate: FormSent(feedbackPostModel=....
```

**Implementation:**
```
 Mopinion.initialise(onActivity, DEPLOYMENT_KEY)
 Mopinion(onActivity, lifecycleOwner)
     .event(form) { state ->
         Timber.i("Formstate: $state")
     }
```

**Comment by Piethot** [comment]
Thanks for addressing this issue. We will investigate this further to come up with a solution. We will provide you with an update as soon as we have more information available.

**Comment by Piethot** [comment]
@Sammekl we have fixed the issue with the spinner. Please let me know if you experience otherwise. Kind regards, Pietetr

**Comment by sammekleijn** [comment]
> @Sammekl we have fixed the issue with the spinner. Please let me know if you experience otherwise. Kind regards, Pietetr

How can I test this fix? There hasn't been a new release since. My issue was in 1.0.13 as well

**Comment by Piethot** [comment]
The fix did not require a new release. Clearing cache should be enough.

**Comment by sammekleijn** [comment]
Thank you! I can confirm, the issue has been solved
